global using System.Text.RegularExpressions;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.Misc;
global using cc1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using BasicConsoleLibrary.Core;
global using cc2 = BasicConsoleLibrary.Core.ConsoleColors;
global using System.Text.Json;
global using bb1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using CommonBasicLibraries.CollectionClasses;
global using rr1 = BasicConsoleLibrary.Resources.FigletListClass;
global using rr2 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.TypeParsingHelpers.SimpleTypeParserRegistrationClass;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using System.Text;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.TypeParsingHelpers;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FlatDataHelpers;
global using BasicConsoleLibrary.Core.Internal;
global using System.Globalization;
global using BasicConsoleLibrary.Core.Extensions;
global using BasicConsoleLibrary.Core.Rendering;
global using BasicConsoleLibrary.Core.Widgets;
global using System.Diagnostics.CodeAnalysis;
global using BasicConsoleLibrary.Core.Widgets.Exceptions;
global using BasicConsoleLibrary.Core.Prompts;
global using BasicConsoleLibrary.Core.Rendering.Borders;
global using BasicConsoleLibrary.Core.Rendering.Borders.Boxes;
global using BasicConsoleLibrary.Core.Rendering.Borders.Tables;
global using BasicConsoleLibrary.Core.Widgets.Table;
global using BasicConsoleLibrary.Core.Live;
global using BasicConsoleLibrary.Core.TimedProcesses;
